export const CATEGORY_LIST_FAILED = 'CATEGORY_LIST_FAILED';
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST';
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS';

export const CATEGORY_DETAILS_FAILED = 'CATEGORY_DETAILS_FAILED';
export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST';
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS';
