export const ORDER_LIST_FAILED = 'ORDER_LIST_FAILED';
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';

export const ORDER_DETAILS_FAILED = 'ORDER_DETAILS_FAILED';
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
