export const TAX_CLASSES_LIST_FAILED = 'TAX_CLASSES_LIST_FAILED';
export const TAX_CLASSES_LIST_REQUEST = 'TAX_CLASSES_LIST_REQUEST';
export const TAX_CLASSES_LIST_SUCCESS = 'TAX_CLASSES_LIST_SUCCESS';

export const TAX_CLASSES_DETAILS_FAILED = 'TAX_CLASSES_DETAILS_FAILED';
export const TAX_CLASSES_DETAILS_REQUEST = 'TAX_CLASSES_DETAILS_REQUEST';
export const TAX_CLASSES_DETAILS_SUCCESS = 'TAX_CLASSES_DETAILS_SUCCESS';
